# Generated by Django 4.2.7 on 2024-05-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adreess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('colony', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='FornitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.adreess')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.order')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.product')),
            ],
        ),
        migrations.CreateModel(
            name='FornitureCombos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('chairs_quantity', models.IntegerField()),
                ('tables_quantity', models.IntegerField()),
                ('type_of_tables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.forniturecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Forniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('total_quantity', models.IntegerField()),
                ('type_of_forniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.forniturecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.customer')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.product')),
            ],
        ),
        migrations.AddField(
            model_name='adreess',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.customer'),
        ),
    ]
