# Generated by Django 4.2.7 on 2023-11-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('cologne', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=50)),
                ('last_name_client', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='FornitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.client')),
            ],
        ),
        migrations.CreateModel(
            name='FornitureCombos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('chairs_quantity', models.IntegerField()),
                ('tables_quantity', models.IntegerField()),
                ('type_of_tables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.forniturecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Forniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('total_quantity', models.IntegerField()),
                ('type_of_forniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.forniturecategory')),
            ],
        ),
        migrations.CreateModel(
            name='DetailedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.product')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.client'),
        ),
    ]
