# Generated by Django 4.2.7 on 2024-05-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mob_mendoza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('colony', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.customer')),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='id_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='id_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id_address',
        ),
        migrations.DeleteModel(
            name='Adreess',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.address'),
            preserve_default=False,
        ),
    ]
