# Generated by Django 4.2.7 on 2023-11-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mob_mendoza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='deadline',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
