# Generated by Django 4.2.7 on 2024-05-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mob_mendoza', '0003_remove_address_client_remove_detailedorder_unit_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mob_mendoza.shoppingcart'),
        ),
    ]
