# Generated by Django 4.2.7 on 2024-05-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mob_mendoza', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('simple', 'simple'), ('pack', 'pack')], default='simple', max_length=10),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_of', to='mob_mendoza.product')),
                ('product_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='mob_mendoza.product')),
            ],
            options={
                'unique_together': {('product_pack', 'product_component')},
            },
        ),
    ]
