# Generated by Django 4.2.7 on 2024-05-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mob_mendoza', '0005_product_description_product_type_component'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FornitureCombos',
        ),
    ]
